# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python38:
      python.version: '3.8'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    pip install --upgrade pip
    pip install pytest pytest-azurepipelines termcolor
  displayName: 'Install dependencies'

- script: |
    pytest -s --exp='400' --ln='400'
  displayName: 'Literal expression'

- script: |
    pytest -s --exp='-250' --ln='-250'
  displayName: 'Negative unary operators on literal expression'

- script: |
    pytest -s --exp='+500' --ln='+500'
  displayName: 'Positive unary operators on literal expression'

- script: |
    pytest -s --exp='16' --ln='2 ^ 4'
  displayName: 'Exponent binary expression'

- script: |
    pytest -s --exp='12' --ln='3 * 4'
  displayName: 'Multiplication binary expression'

- script: |
    pytest -s --exp='420' --ln='210 + 210'
  displayName: 'Addition binary expression'

- script: |
    pytest -s --exp='4' --ln='1000 - 996'
  displayName: 'Subtraction binary expression'

- script: |
    pytest -s --exp='8' --ln='89 % 9'
  displayName: 'Modulo binary expression'

- script: |
    pytest -s --exp='35' --ln='(2 - 2) * 2 + ((5 + 2) * 5)'
  displayName: 'Parenthesized arguments'
  
- script: |
    pytest -s --exp='4' --ln='+1*(2^(-2*(-1)))'
  displayName: 'Combination of all expression types'

- script: |
    pytest -s --exp='1' --ln='+--+1'
  displayName: 'Multiple unary operators on literal'